---
# This is an exemplary config file. If you use this program for the first time, you can also specify everything step
# by step in the command line; the program will then generate the correct config file.

# Enter the total order.
max_order: 2
# Give a unique name (integer) to every operator, so that you can distinguish them. You can take the operator index as
# its name, provided that they are unique. The list 'operators_left' contains all operators on the left side of the
# tensor product and the list 'operators_right' all operators on the right side of the tensor product.
operators_left: [-5, -4, -3, -2, -1]
operators_right: [1, 2, 3, 4, 5]
# Enter the operator indices. In Andi's case, enter the unperturbed energy differences caused by the operators. In Lea's
# case, enter the indices of the operators prior to transposition.
indices:
  -5: -2
  -4: -1
  -3: 0
  -2: 1
  -1: 2
  1: -2
  2: -1
  3: 0
  4: 1
  5: 2
# Manually insert the solution for the coefficient functions with non-vanishing starting condition as strings.
starting_conditions:
  ((-5,), ()): '1'
  ((-3,), ()): '1'
  ((-1,), ()): '1'
  ((), (1,)): '-1'
  ((), (3,)): '-1'
  ((), (5,)): '-1'
  ((-4,), (4,)): '1'
  ((-2, -4), ()): '-1/2'
  ((), (2, 4)): '-1/2'
# Introduce band-diagonality, i.e., write down the largest sum of indices occurring in the starting conditions.
max_energy: 2
...
