---
# This is an exemplary config file. If you use this program for the first time, you can also specify everything directly
# in the file 'main.py'; the program will then generate the correct config file.

# Enter the total order.
max_order: 2
# Give a unique name to every operator, so that you can distinguish them. You can take the operator index as its name,
# provided that they are unique. The list 'operators_left' contains all operators on the left side of the tensor product
# and the list 'operators_right' all operators on the right side of the tensor product.
operators_left: [8, 9, 10, 11, 12]
operators_right: [18, 19, 20, 21, 22]
# Enter the operator indices. In Andi's case, enter the unperturbed energy differences caused by the operators. In Lea's
# case, enter the indices of the operators prior to transposition.
indices:
  8: -2
  9: -1
  10: 0
  11: 1
  12: 2
  18: -2
  19: -1
  20: 0
  21: 1
  22: 2
# Manually insert the solution for the coefficient functions with non-vanishing starting condition as strings.
starting_conditions:
  ((8,), ()): '1'
  ((10,), ()): '1'
  ((12,), ()): '1'
  ((), (18,)): '-1'
  ((), (20,)): '-1'
  ((), (22,)): '-1'
  ((9,), (21,)): '1'
  ((11, 9), ()): '-1/2'
  ((), (19, 21)): '-1/2'
# Introduce band-diagonality, i.e., write down the largest sum of indices occurring in the starting conditions.
max_energy: 2
...
